# (https://docs.docker.com/compose/compose-file/)
# (https://docs.docker.com/compose/compose-file/compose-file-v3/)

version: '3'

# (https://blog.code4hire.com/2018/06/define-named-volume-with-host-mount-in-the-docker-compose-file/)
volumes:

  wordpress_database:
    driver: local
    driver_opts:
      device: /home/alf/data/wordpress_database
      o: bind
      type: none

  wordpress_files:
    driver: local
    driver_opts:
      device: /home/alf/data/wordpress_files
      o: bind
      type: none


networks:
  inception:

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        - MDB_HOST=${MDB_HOST}
        - MDB_NAME=${MDB_NAME}
        - MDB_PASS=${MDB_PASS}
        - MDB_PASS_ROOT=${MDB_PASS_ROOT}
        - MDB_USER=${MDB_USER}
    ports:
      - 3306:3306
    volumes:
      - wordpress_database:/var/lib/mysql
    networks: 
      - inception
    restart: unless-stopped # https://stackoverflow.com/questions/61725195/difference-in-docker-restart-policy-between-on-failure-and-unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    build:
      context: ./requirements/wordpress
    ports:
      - 9000:9000
    environment:
      - WORDPRESS_DB_HOST=${WP_DB_HOST}
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASS}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    env_file: .env
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped